import { Router } from 'express';
import authRoutes from './authRoutes.js';
import userRoutes from './userRoutes.js';
import profileRoutes from './profileRoutes.js';
import bookmarkRoutes from './bookmarkRoutes.js';
import departmentRoutes from './departmentRoutes.js';
import courseRoutes from './courseRoutes.js';
import batchRoutes from './batchRoutes.js';
import semesterRoutes from './semesterRoutes.js';
import categoryRoutes from './categoryRoutes.js';
import chapterRoutes from './chapterRoutes.js';
import topicRoutes from './topicRoutes.js';
import fileRoutes from './fileRoutes.js';
import adminRoutes from './adminRoutes.js';
import superAdminRoutes from './superAdminRoutes.js';
import searchRoutes from './searchRoutes.js';
import analyticsRoutes from './analyticsRoutes.js';
import reviewRoutes from './reviewRoutes.js';
import facultyRoutes from './facultyRoutes.js';
import feedbackRoutes from './feedbackRoutes.js';
import noticeRoutes from './noticeRoutes.js';
import assignmentRoutes from './assignmentRoutes.js';
import questionRoutes from './questionRoutes.js';
import quizRoutes from './quizRoutes.js';
import messageRoutes from './messageRoutes.js';
import emailRoutes from './emailRoutes.js';
import roleRoutes from './roleRoutes.js';
import courseEnrollmentRoutes from './courseEnrollmentRoutes.js';
import publicExamRoutes from './publicExamRoutes.js';
import notificationRoutes from './notificationRoutes.js';
import adminNotificationRoutes from './adminNotificationRoutes.js';
import studentIdRoutes from './studentIdRoutes.js';
import deviceRoutes from './deviceRoutes.js';

const router = Router();

router.get('/health', (req, res) => res.json({ success: true, message: 'ok' }));

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/profile', profileRoutes);
router.use('/bookmarks', bookmarkRoutes);
router.use('/departments', departmentRoutes);
router.use('/courses', courseRoutes);
router.use('/batches', batchRoutes);
router.use('/semesters', semesterRoutes);
router.use('/categories', categoryRoutes);
router.use('/chapters', chapterRoutes);
router.use('/topics', topicRoutes);
router.use('/files', fileRoutes);
router.use('/admin', adminRoutes);
router.use('/super-admin', superAdminRoutes);
router.use('/search', searchRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/reviews', reviewRoutes);
router.use('/faculty', facultyRoutes);
router.use('/feedback', feedbackRoutes);
router.use('/notices', noticeRoutes);
router.use('/assignments', assignmentRoutes);
router.use('/questions', questionRoutes);
router.use('/quizzes', quizRoutes);
router.use('/messages', messageRoutes);
router.use('/emails', emailRoutes);
router.use('/roles', roleRoutes);
router.use('/course-enrollments', courseEnrollmentRoutes);
router.use('/public-exams', publicExamRoutes);
router.use('/notifications', notificationRoutes);
router.use('/admin/notifications', adminNotificationRoutes);
router.use('/student-id', studentIdRoutes);
router.use('/devices', deviceRoutes);

export default router;
