import mammoth from 'mammoth';
import { QUESTION_TYPES } from '../models/Question.js';

// Plain-text question markup this parser understands (see the example file
// generated by server/scripts/generateQuestionImportTemplate.js):
//
//   Q1. What is the capital of France?
//   A) London
//   B) Paris *          <- a trailing * marks a correct option
//   C) Rome
//   D) Berlin
//   Explanation: Paris has been the capital of France since 508 AD.
//   Marks: 2
//   Difficulty: easy
//   Tags: geography, capitals
//
// Every question block starts with a line matching `Q<number>.` (or `)`/`:`)
// — everything up to the next such line (or end of document) belongs to that
// question. The first line's text (after stripping the "Q1." marker) plus
// any immediately-following plain lines (before the first recognized
// option/directive line) form the question text, so a question can span
// multiple lines. Recognized directive lines (case-insensitive, in any
// order, any subset): `Type:`, `Answer:`, `Explanation:`, `Marks:`,
// `Negative:`, `Difficulty:`, `Tags:`, `Tolerance:`, plus option lines
// `A) ...`/`A. ...` (A-F) and matching-pair lines `Left: ... | Right: ...`.
//
// `Type:` is optional for mcq/multi_select/true_false/matching (inferred
// from the options/pairs actually present) but required for
// long_answer (nothing else to infer it from) and recommended for
// numerical/short_answer/fill_blank to disambiguate short_answer vs
// fill_blank vs numerical, all of which otherwise just look like "one
// Answer: line, no options".

const Q_MARKER = /^Q\s*\d+\s*[.):]\s*/i;
const OPTION_LINE = /^([A-F])[).]\s*(.*)$/i;
const DIRECTIVE_LINE = /^(Type|Answer|Explanation|Marks|Negative|Difficulty|Tags|Tolerance)\s*:\s*(.*)$/i;
const MATCH_PAIR_LINE = /^Left\s*:\s*(.*?)\s*\|\s*Right\s*:\s*(.*)$/i;
const TRAILING_STAR = /\*\s*$/;

function splitIntoBlocks(rawText) {
  const lines = rawText.split(/\r?\n/).map((l) => l.trim());
  const blocks = [];
  let current = null;
  for (const line of lines) {
    if (Q_MARKER.test(line)) {
      if (current) blocks.push(current);
      current = [line];
    } else if (current && line) {
      current.push(line);
    }
  }
  if (current) blocks.push(current);
  return blocks;
}

function parseOptionLine(line) {
  const m = line.match(OPTION_LINE);
  if (!m) return null;
  let text = m[2].trim();
  let isCorrect = false;
  if (TRAILING_STAR.test(text)) {
    isCorrect = true;
    text = text.replace(TRAILING_STAR, '').trim();
  }
  return { text, isCorrect };
}

// Parses one question block (array of trimmed, non-empty lines, first one
// carrying the "Q<n>." marker) into a draft question object, or throws a
// short human-readable Error describing what's wrong/missing/ambiguous.
function parseBlock(lines) {
  const firstLine = lines[0].replace(Q_MARKER, '').trim();
  const textLines = firstLine ? [firstLine] : [];

  const options = [];
  const matchingPairs = [];
  const directives = {};
  let sawStructureLine = false;

  for (let i = 1; i < lines.length; i++) {
    const line = lines[i];
    const pairMatch = line.match(MATCH_PAIR_LINE);
    const optionResult = parseOptionLine(line);
    const directiveMatch = line.match(DIRECTIVE_LINE);

    if (pairMatch) {
      matchingPairs.push({ left: pairMatch[1].trim(), right: pairMatch[2].trim() });
      sawStructureLine = true;
    } else if (optionResult) {
      options.push(optionResult);
      sawStructureLine = true;
    } else if (directiveMatch) {
      const key = directiveMatch[1].toLowerCase();
      directives[key] = directiveMatch[2].trim();
      sawStructureLine = true;
    } else if (!sawStructureLine) {
      // Plain continuation line — only valid before any option/directive
      // has started, i.e. still part of a multi-line question text.
      textLines.push(line);
    }
    // A plain line appearing AFTER structure has started is silently
    // ignored — most likely stray wrapped text from the source document's
    // own line breaks, not something we can safely attribute anywhere.
  }

  const text = textLines.join(' ').trim();
  if (!text) throw new Error('No question text found');

  let type = directives.type ? directives.type.toLowerCase().replace(/\s+/g, '_') : '';
  if (type && !QUESTION_TYPES.includes(type)) {
    throw new Error(`Unknown Type: "${directives.type}"`);
  }

  // Infer the type when not explicitly given, from whatever structure IS present.
  if (!type) {
    if (matchingPairs.length >= 2) {
      type = 'matching';
    } else if (options.length >= 2) {
      const correctCount = options.filter((o) => o.isCorrect).length;
      if (correctCount > 1) {
        type = 'multi_select';
      } else if (options.length === 2 && options.every((o) => ['true', 'false'].includes(o.text.trim().toLowerCase()))) {
        type = 'true_false';
      } else {
        type = 'mcq';
      }
    } else if (directives.answer) {
      type = text.includes('___') ? 'fill_blank' : 'short_answer';
    } else {
      throw new Error('Could not determine question type — add options, an Answer: line, or an explicit Type: line');
    }
  }

  const draft = {
    type,
    text,
    explanation: directives.explanation || '',
    defaultMarks: directives.marks ? Number(directives.marks) : 1,
    negativeMarks: directives.negative ? Number(directives.negative) : 0,
    difficulty: ['easy', 'medium', 'hard'].includes((directives.difficulty || '').toLowerCase())
      ? directives.difficulty.toLowerCase()
      : 'medium',
    tags: directives.tags
      ? [...new Set(directives.tags.split(',').map((t) => t.trim().toLowerCase()).filter(Boolean))]
      : [],
    options: [],
    correctTextAnswers: [],
    matchingPairs: [],
    numericalAnswer: null,
    numericalTolerance: 0,
  };

  switch (type) {
    case 'mcq':
    case 'true_false':
      if (options.length < 2) throw new Error(`${type} needs at least 2 options (A), B), ...)`);
      if (options.filter((o) => o.isCorrect).length !== 1) {
        throw new Error(`${type} needs exactly one option marked correct (trailing *)`);
      }
      draft.options = options;
      break;
    case 'multi_select':
      if (options.length < 2) throw new Error('multi_select needs at least 2 options');
      if (!options.some((o) => o.isCorrect)) throw new Error('multi_select needs at least one option marked correct (trailing *)');
      draft.options = options;
      break;
    case 'short_answer':
      if (!directives.answer) throw new Error('short_answer needs an Answer: line');
      // Semicolon-separated alternatives — any one of them counts as correct.
      draft.correctTextAnswers = directives.answer.split(';').map((a) => a.trim()).filter(Boolean);
      break;
    case 'fill_blank':
      if (!directives.answer) throw new Error('fill_blank needs an Answer: line');
      // Pipe-separated, one per blank, IN ORDER (a fill_blank question can
      // have more than one ___ blank in its text).
      draft.correctTextAnswers = directives.answer.split('|').map((a) => a.trim()).filter(Boolean);
      break;
    case 'matching':
      if (matchingPairs.length < 2) throw new Error('matching needs at least 2 "Left: ... | Right: ..." lines');
      draft.matchingPairs = matchingPairs;
      break;
    case 'numerical': {
      if (!directives.answer || Number.isNaN(Number(directives.answer))) {
        throw new Error('numerical needs a numeric Answer: line');
      }
      draft.numericalAnswer = Number(directives.answer);
      draft.numericalTolerance = directives.tolerance && !Number.isNaN(Number(directives.tolerance)) ? Number(directives.tolerance) : 0;
      break;
    }
    case 'long_answer':
      break; // free text, manually graded — nothing further required
    default:
      throw new Error(`Unsupported type "${type}"`);
  }

  return draft;
}

/**
 * Parses a .docx file's raw text into question drafts.
 * @param {Buffer} buffer
 * @returns {Promise<{ results: Array<{index:number, ok:true, data:object} | {index:number, ok:false, rawText:string, message:string}> }>}
 */
export async function parseDocxQuestions(buffer) {
  const { value: rawText } = await mammoth.extractRawText({ buffer });
  const blocks = splitIntoBlocks(rawText);

  if (!blocks.length) {
    throw new Error('No questions found — each question must start with a line like "Q1." followed by the question text');
  }

  const results = blocks.map((lines, index) => {
    try {
      const data = parseBlock(lines);
      return { index, ok: true, data };
    } catch (err) {
      return { index, ok: false, rawText: lines[0], message: err.message };
    }
  });

  return { results };
}
