import { test, describe } from 'node:test';
import assert from 'node:assert/strict';
import { renderTimetablePdf } from './timetablePdf.js';
import { formatClock, timetableFileName, DAY_NAMES } from './timetableService.js';

// The routine PDF is generated by hand (no Chromium, no PDF library), so its
// structure and its page breaks are worth pinning: a broken xref makes a file
// that opens as "damaged" everywhere, and an off-by-one page break silently drops
// a row of classes.

const pdf = (timetable) => renderTimetablePdf(timetable).toString('latin1');

/** Every /Type /Page object's offset must actually point at its object header. */
function assertValidXref(text) {
  const start = text.lastIndexOf('startxref');
  assert.ok(start > 0, 'has startxref');
  const offset = Number.parseInt(text.slice(start + 9).trim(), 10);
  assert.equal(text.slice(offset, offset + 4), 'xref', 'startxref points at the xref table');

  const lines = text.slice(offset).split('\n');
  const count = Number.parseInt(lines[1].split(' ')[1], 10);
  for (let i = 1; i < count; i += 1) {
    const objectOffset = Number.parseInt(lines[2 + i].slice(0, 10), 10);
    assert.ok(
      text.startsWith(`${i} 0 obj`, objectOffset),
      `object ${i} offset resolves (got ${JSON.stringify(text.slice(objectOffset, objectOffset + 12))})`
    );
  }
  return count;
}

function buildTimetable({ slotCount = 3, days = DAY_NAMES.slice(0, 4), entriesPerCell = 1 } = {}) {
  const slots = [];
  const cells = new Map();
  for (let i = 0; i < slotCount; i += 1) {
    const start = String(8 + i).padStart(2, '0') + ':00';
    const end = String(8 + i).padStart(2, '0') + ':50';
    const key = `${start}-${end}`;
    slots.push({ key, start, end, label: `${start} - ${end}` });
    for (const day of days) {
      const list = [];
      for (let e = 0; e < entriesPerCell; e += 1) {
        list.push({
          courseCode: `CSE-2${day.index}${e}`,
          courseName: `Course ${day.index}`,
          facultyName: `Teacher ${day.index}`,
          roomNumber: `30${day.index}`,
          classType: 'REGULAR',
          deliveryMode: 'OFFLINE',
          group: 'BOTH',
        });
      }
      cells.set(`${day.index}|${key}`, list);
    }
  }
  return {
    scope: {
      department: { name: 'Computer Science & Engineering', code: 'CSE' },
      batch: { name: 'BATCH-14', code: 'BATCH-14' },
      semester: { name: '2nd Semester', code: 'SEM-2' },
    },
    days,
    slots,
    cells,
    classCount: slots.length * days.length,
    generatedAt: new Date(),
  };
}

describe('renderTimetablePdf', () => {
  test('produces a structurally valid single-page PDF', () => {
    const text = pdf(buildTimetable());
    assert.ok(text.startsWith('%PDF-1.4'));
    assert.ok(text.trimEnd().endsWith('%%EOF'));
    assert.ok(text.includes('/Type /Catalog'));
    assertValidXref(text);
    assert.equal((text.match(/\/Type \/Page[^s]/g) || []).length, 1);
    assert.ok(text.includes('Page 1 of 1'));
  });

  test('writes the scope, the title and the classes', () => {
    const text = pdf(buildTimetable());
    assert.ok(text.includes('CLASS ROUTINE'));
    assert.ok(text.includes('Computer Science & Engineering'));
    assert.ok(text.includes('BATCH-14'));
    assert.ok(text.includes('2nd Semester'));
    assert.ok(text.includes('CSE-200'));
    assert.ok(text.includes('Asia/Dhaka'));
  });

  test('starts a new page rather than splitting a row, and numbers every page', () => {
    const text = pdf(buildTimetable({ slotCount: 40 }));
    const pages = (text.match(/\/Type \/Page[^s]/g) || []).length;
    assert.ok(pages > 1, `expected a page break, got ${pages} page(s)`);
    for (let i = 1; i <= pages; i += 1) {
      assert.ok(text.includes(`Page ${i} of ${pages}`), `page ${i} footer`);
    }
    assertValidXref(text);
  });

  test('still renders when the scope has no classes at all', () => {
    const text = pdf({ ...buildTimetable(), slots: [], cells: new Map(), classCount: 0 });
    assert.ok(text.startsWith('%PDF-1.4'));
    assertValidXref(text);
    assert.ok(text.includes('No classes are scheduled'));
    assert.ok(text.includes('0 classes'));
  });

  test('summarises overflow in a cell instead of growing the row forever', () => {
    const text = pdf(buildTimetable({ entriesPerCell: 5 }));
    assert.ok(text.includes('+2 more'));
  });
});

describe('formatClock', () => {
  test('renders 24-hour times as 12-hour clock times', () => {
    assert.equal(formatClock('08:00'), '08:00 AM');
    assert.equal(formatClock('00:05'), '12:05 AM');
    assert.equal(formatClock('12:00'), '12:00 PM');
    assert.equal(formatClock('13:30'), '01:30 PM');
    assert.equal(formatClock('23:59'), '11:59 PM');
  });

  test('passes an unusable value straight through', () => {
    assert.equal(formatClock(''), '');
    assert.equal(formatClock('nonsense'), 'nonsense');
  });
});

describe('timetableFileName', () => {
  test('builds a filesystem-safe name from the scope', () => {
    assert.equal(
      timetableFileName({
        department: { name: 'Computer Science & Engineering', code: 'CSE' },
        batch: { code: 'BATCH-14' },
        semester: { name: '2nd Semester' },
      }),
      'routine-CSE-BATCH-14-2nd-Semester.pdf'
    );
  });

  test('falls back to the department name and survives a partial scope', () => {
    assert.equal(timetableFileName({ department: { name: 'Law' } }), 'routine-Law.pdf');
    assert.equal(timetableFileName({ department: null }), 'routine.pdf');
  });
});
